apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrations-{{ .Chart.AppVersion }}"
  labels:
    {{- include "camerahub.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "camerahub.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-wait-for-db"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
        - "pod"
        - "-lapp.kubernetes.io/component=pgpool"
      containers:
      - name: {{ .Chart.Name }}-migrations
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args: ['true']
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CAMERAHUB_DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: CAMERAHUB_DB_PASS
          - name: CAMERAHUB_DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: CAMERAHUB_DB_USER            
          - name: CAMERAHUB_DB_HOST
            value: {{ .Release.Name }}-postgresql-ha-pgpool
          - name: CAMERAHUB_DB_NAME
            value: {{ .Values.global.postgresql.database }}
          - name: CAMERAHUB_DB_PORT
            value: "5432"
          - name: CAMERAHUB_DB_ENGINE
            value: django.db.backends.postgresql
          - name: CAMERAHUB_PROD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: CAMERAHUB_PROD
                optional: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}
